# Generated by Django 5.2.16 on 2026-07-27 07:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('dept', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'v2_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('menu_key', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('read', 'read'), ('write', 'write'), ('update', 'update'), ('delete', 'delete')], default='read', max_length=10)),
                ('allowed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'v2_role_permissions',
                'constraints': [models.UniqueConstraint(fields=('role', 'menu_key', 'action'), name='uniq_role_menu_action')],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=50)),
                ('tech', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(blank=True, default='nodata', max_length=20)),
                ('status_2g', models.CharField(blank=True, default='', max_length=20)),
                ('status_3g', models.CharField(blank=True, default='', max_length=20)),
                ('kpi_entered', models.BooleanField(default=False)),
                ('kpi_entered_2g', models.BooleanField(default=False)),
                ('kpi_entered_3g', models.BooleanField(default=False)),
                ('kpi_date', models.CharField(blank=True, default='', max_length=32)),
                ('rrc', models.FloatField(blank=True, null=True)),
                ('erab', models.FloatField(blank=True, null=True)),
                ('call_setup', models.FloatField(blank=True, null=True)),
                ('call_drop', models.FloatField(blank=True, null=True)),
                ('svc_drop', models.FloatField(blank=True, null=True)),
                ('intra_ho', models.FloatField(blank=True, null=True)),
                ('inter_ho', models.FloatField(blank=True, null=True)),
                ('inter_rat', models.FloatField(blank=True, null=True)),
                ('ip_thru', models.FloatField(blank=True, null=True)),
                ('ip_thru_dl', models.FloatField(blank=True, null=True)),
                ('ip_thru_ul', models.FloatField(blank=True, null=True)),
                ('ip_lat', models.FloatField(blank=True, null=True)),
                ('prb', models.FloatField(blank=True, null=True)),
                ('prb_dl', models.FloatField(blank=True, null=True)),
                ('prb_ul', models.FloatField(blank=True, null=True)),
                ('bearer_util', models.FloatField(blank=True, null=True)),
                ('lic_util', models.FloatField(blank=True, null=True)),
                ('cell_avail', models.FloatField(blank=True, null=True)),
                ('volte_setup', models.FloatField(blank=True, null=True)),
                ('csfb', models.FloatField(blank=True, null=True)),
                ('kpi_2g_json', models.JSONField(blank=True, null=True)),
                ('kpi_3g_json', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v2_sites',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(blank=True, default='', max_length=100)),
                ('sector', models.CharField(blank=True, default='', max_length=20)),
                ('tech', models.CharField(blank=True, default='', max_length=20)),
                ('local_cell_id', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('azimuth', models.FloatField(blank=True, null=True)),
                ('mech_tilt', models.FloatField(blank=True, null=True)),
                ('elec_tilt', models.FloatField(blank=True, null=True)),
                ('pci', models.IntegerField(blank=True, null=True)),
                ('scrambling_code', models.IntegerField(blank=True, null=True)),
                ('bcch', models.IntegerField(blank=True, null=True)),
                ('bsic', models.IntegerField(blank=True, null=True)),
                ('kpi_json', models.JSONField(blank=True, null=True)),
                ('kpi_date', models.CharField(blank=True, default='', max_length=32)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='core.site')),
            ],
            options={
                'db_table': 'v2_sectors',
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['region', 'district'], name='v2_sites_region_b8405d_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['site'], name='v2_sectors_site_id_3c84f7_idx'),
        ),
    ]
