# Generated by Django 5.2.16 on 2026-07-27 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiThreshold',
            fields=[
                ('kpi_key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('warn', models.FloatField(blank=True, null=True)),
                ('crit', models.FloatField(blank=True, null=True)),
                ('hi', models.BooleanField(default=False)),
                ('max', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'v2_kpi_thresholds',
            },
        ),
        migrations.CreateModel(
            name='SiteAssignment',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tree_assignment', serialize=False, to='core.site')),
                ('folder_id', models.CharField(blank=True, max_length=64, null=True)),
                ('subfolder_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'v2_site_assignments',
            },
        ),
        migrations.CreateModel(
            name='TreeFolder',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'v2_tree_folders',
            },
        ),
        migrations.CreateModel(
            name='TreeSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('custom_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'v2_tree_settings',
            },
        ),
        migrations.CreateModel(
            name='TreeSubfolder',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='core.treefolder')),
            ],
            options={
                'db_table': 'v2_tree_subfolders',
            },
        ),
    ]
