# Generated by Django 5.2.16 on 2026-07-28
#
# Hand-written to match exactly what `makemigrations core` generates from
# the current models.py (confirmed against the real autodetector output,
# 2026-07-28 — same operation list/order, same auto-generated filename).
# Written directly to the host source tree rather than left to be created
# inside a running container: the `django` service has no source bind
# mount (see docker-compose.yml), so a migration file created via
# `docker compose exec django python manage.py makemigrations` only ever
# exists in that specific container's ephemeral writable layer — it's
# invisible to the host and to every future image build, and is lost on
# any container recreation. That mismatch (confirmed live, 2026-07-28)
# is what caused `migrate` to alternately claim "no migrations to apply"
# and then fail applying a migration that live-schema evidence showed had
# never actually persisted. Writing the file here makes it a real,
# durable part of the repo/image, closing that gap for good — see
# docs/RUNBOOK.md for the fuller writeup.
#
# Covers, in one migration: the arbitrary-depth tree redesign (TreeFolder
# gains parent/lat/lng, TreeSubfolder is retired, SiteAssignment drops
# subfolder_id — Phase 2, 2026-07-27) together with the two Phase 3
# additions built after it (Site.rssi/Site.load — task #38 — and the new
# KpiSnapshot model backing KPI Trend).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_kpithreshold_siteassignment_treefolder_treesettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteassignment',
            name='subfolder_id',
        ),
        migrations.AddField(
            model_name='site',
            name='load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='rssi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treefolder',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treefolder',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.treefolder'),
        ),
        migrations.CreateModel(
            name='KpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('rrc', models.FloatField(blank=True, null=True)),
                ('erab', models.FloatField(blank=True, null=True)),
                ('call_setup', models.FloatField(blank=True, null=True)),
                ('call_drop', models.FloatField(blank=True, null=True)),
                ('svc_drop', models.FloatField(blank=True, null=True)),
                ('intra_ho', models.FloatField(blank=True, null=True)),
                ('inter_ho', models.FloatField(blank=True, null=True)),
                ('inter_rat', models.FloatField(blank=True, null=True)),
                ('ip_thru', models.FloatField(blank=True, null=True)),
                ('ip_lat', models.FloatField(blank=True, null=True)),
                ('prb', models.FloatField(blank=True, null=True)),
                ('bearer_util', models.FloatField(blank=True, null=True)),
                ('lic_util', models.FloatField(blank=True, null=True)),
                ('cell_avail', models.FloatField(blank=True, null=True)),
                ('rssi', models.FloatField(blank=True, null=True)),
                ('load', models.FloatField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='core.site')),
            ],
            options={
                'db_table': 'v2_kpi_snapshots',
            },
        ),
        migrations.DeleteModel(
            name='TreeSubfolder',
        ),
        migrations.AddIndex(
            model_name='kpisnapshot',
            index=models.Index(fields=['site', 'date'], name='v2_kpi_snap_site_id_e7875c_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpisnapshot',
            constraint=models.UniqueConstraint(fields=('site', 'date'), name='uniq_kpi_snapshot_site_date'),
        ),
    ]
