# Generated by Django 5.2.16 on 2026-07-28
#
# Hand-written directly to the host source tree, same as 0004 — the
# `django` service has no source bind mount (see docker-compose.yml), so
# `makemigrations` run via `docker compose exec` only ever writes into
# that container's ephemeral layer and is lost on recreation. See
# feedback_docker_migrations_no_persist memory / docs/RUNBOOK.md for the
# full incident writeup. Always verify a migration file actually landed
# here on host disk before telling the user to `migrate`.
#
# Adds the AuditHistory model backing RF Audit (Phase 3f) — the only
# remaining Phase 3 reporting-suite item.
#
# UPDATE 2026-07-28: the AddIndex name below was originally a guessed
# hash (not cross-checked — no docker access when this file was first
# written), which caused a real, confirmed problem: every subsequent
# `makemigrations core` regenerated a RenameIndex migration to reconcile
# the guess against Django's real computed name, and applying that rename
# failed outright (`relation "..." does not exist`) because the guessed
# name never actually matched what got created in Postgres. Fixed by
# replacing the guess with the exact name Django's real autodetector
# reported on the user's machine (`v2_audit_hi_site_id_7d6232_idx`) — see
# docs/RUNBOOK.md's Phase 4 section for the full incident writeup. This
# is now the correct, stable name; `makemigrations core` should report
# "No changes detected" for this index going forward.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_remove_siteassignment_subfolder_id_site_load_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_reports', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_history', to='core.site')),
            ],
            options={
                'db_table': 'v2_audit_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='audithistory',
            # Real name confirmed against a live `makemigrations core` run
            # on 2026-07-28 (the guessed name this replaced produced a
            # spurious RenameIndex on every subsequent makemigrations —
            # fixed by baking in Django's actual computed name directly).
            index=models.Index(fields=['site', '-created_at'], name='v2_audit_hi_site_id_7d6232_idx'),
        ),
    ]
