# Generated by Django 5.2.16 on 2026-07-28
#
# Hand-written directly to the host source tree, per the standing rule
# from 0004/0005 — the `django` service has no source bind mount, so a
# container-run `makemigrations` never persists past that container's
# life. See feedback_docker_migrations_no_persist / docs/RUNBOOK.md.
# UPDATE 2026-07-28: the two AddIndex names below were originally guessed
# (not cross-checked — no docker access when first written). Same
# real, confirmed problem as 0005's index: `makemigrations core` kept
# regenerating a RenameIndex to reconcile the guesses, and applying it
# failed with `relation "..." does not exist`. Fixed by swapping in the
# exact names Django's real autodetector reported on the user's machine
# — see docs/RUNBOOK.md's Phase 4 section for the full writeup.
#
# Phase 4a — DriveTestSession/DriveTestSample, the storage layer behind
# the Drive-Test Data Manager. See DriveTestSession's model docstring for
# the full scope decision (client-side parsing first, Go job wiring is a
# follow-up) and why this schema matches v1's real `dt_sessions`/
# `dt_records` server tables rather than the migration plan's own sketch.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_audithistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('tech', models.CharField(blank=True, default='4G', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('uploaded_date', models.DateField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dt_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v2_dt_sessions',
                'ordering': ['-date', '-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='DriveTestSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(blank=True, default='', max_length=32)),
                ('date', models.CharField(blank=True, default='', max_length=16)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('rsrp', models.FloatField(blank=True, null=True)),
                ('rsrq', models.FloatField(blank=True, null=True)),
                ('sinr', models.FloatField(blank=True, null=True)),
                ('dl', models.FloatField(blank=True, null=True)),
                ('pci', models.IntegerField(blank=True, null=True)),
                ('serving_site_id', models.CharField(blank=True, max_length=64, null=True)),
                ('serving_site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('serving_sector', models.CharField(blank=True, max_length=20, null=True)),
                ('serving_cell_name', models.CharField(blank=True, max_length=100, null=True)),
                ('serving_local_cell_id', models.IntegerField(blank=True, null=True)),
                ('serving_dist_km', models.FloatField(blank=True, null=True)),
                ('cell_role', models.CharField(blank=True, choices=[('serving', 'Serving'), ('neighbor', 'Neighbor')], default='serving', max_length=10)),
                ('rx_qual', models.FloatField(blank=True, null=True)),
                ('bcch', models.IntegerField(blank=True, null=True)),
                ('bsic', models.IntegerField(blank=True, null=True)),
                ('rscp', models.FloatField(blank=True, null=True)),
                ('ecno', models.FloatField(blank=True, null=True)),
                ('scrambling_code', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.drivetestsession')),
            ],
            options={
                'db_table': 'v2_dt_samples',
            },
        ),
        migrations.AddIndex(
            model_name='drivetestsession',
            # Real name confirmed against a live `makemigrations core` run
            # on 2026-07-28 (see 0005's AddIndex comment — same fix).
            index=models.Index(fields=['-date', '-saved_at'], name='v2_dt_sessi_date_114a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='drivetestsample',
            index=models.Index(fields=['session'], name='v2_dt_sampl_session_bdeb38_idx'),
        ),
    ]
