# Generated by Django 5.2.16 on 2026-08-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_drivetestsession_drivetestsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_tag', models.CharField(db_index=True, max_length=32)),
                ('label', models.CharField(max_length=40)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('color', models.CharField(max_length=9)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'v2_dt_bands',
                'ordering': ['metric_tag', 'sort_order'],
            },
        ),
    ]
