# Generated by Django 5.2.16 on 2026-08-08 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_dtband_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('link_type', models.CharField(choices=[('route', 'Internal route'), ('external', 'External URL')], default='route', max_length=10)),
                ('path', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('access', models.CharField(choices=[('all', 'Any signed-in user'), ('permission', 'Governed by Permissions matrix'), ('admin', 'Admin + superadmin only'), ('superadmin', 'Superadmin only')], default='all', max_length=12)),
                ('permission_key', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'db_table': 'v2_menu_items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
