# Generated by Django 5.2.16 on 2026-08-08 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seed_menuitem_icons_and_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key', models.CharField(max_length=64)),
                ('order', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v2_dashboard_card_config',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'card_key'), name='uniq_user_dashboard_card')],
            },
        ),
    ]
