# Generated by Django 5.2.16 on 2026-08-08 02:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dashboardcardconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('app_name', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.models.branding_logo_upload_path)),
            ],
            options={
                'db_table': 'v2_branding_settings',
            },
        ),
    ]
