# Generated by Django 5.2.16 on 2026-08-08 03:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_branding_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.menu_icon_upload_path),
        ),
    ]
