# Generated by Django 5.2.16 on 2026-08-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_menuitem_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='login_button_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='login_password_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='login_subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='login_username_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
