# Generated by Django 5.2.16 on 2026-08-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_seed_api_access_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_source',
            field=models.CharField(choices=[('local', 'Local password'), ('sso', 'Keycloak SSO')], default='local', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='sso_subject',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
