# PostGIS adoption (2026-08-25). Generated by `makemigrations core`, then
# hand-renamed from the autodetector's default name and extended with the
# RunSQL backfill below — see GeoSyncQuerySet in models.py for why new
# writes stay in sync automatically, and this migration's own comment
# below for why EXISTING rows need a one-time backfill.
#
# django.contrib.gis.db.backends.postgis runs `CREATE EXTENSION IF NOT
# EXISTS postgis` itself on first migrate against a DB role with the
# needed privilege (docker-compose.yml's `db` is postgis/postgis, which
# grants that to the default role) — no explicit CreateExtension
# operation needed here.

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_seed_menupermission_defaults'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drivetestsample',
            name='v2_dt_sampl_lat_1ab414_idx',
        ),
        migrations.AddField(
            model_name='drivetestsample',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='site',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        # Backfill for rows that existed before this migration — new writes
        # sync `location` from lat/lng automatically (GeoSyncQuerySet), but
        # that only runs going forward. A one-time UPDATE covers whatever
        # was already in the table (relevant the day this lands on a real
        # deployment with existing data; a no-op on a fresh/empty DB, which
        # is what this branch's own local dev DB is). Plain SQL rather than
        # RunPython — a straight UPDATE...WHERE is one statement Postgres
        # can run directly, no need to round-trip every row through the ORM
        # (this table alone can hold 120,000+ rows per upload batch).
        migrations.RunSQL(
            sql=(
                "UPDATE v2_sites SET location = ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography "
                "WHERE lat IS NOT NULL AND lng IS NOT NULL AND location IS NULL;"
                "UPDATE v2_dt_samples SET location = ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography "
                "WHERE lat IS NOT NULL AND lng IS NOT NULL AND location IS NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
