# Live Site Directory sync (2026-08-26) — see Site model's own field
# comments in models.py and core/live_sites.py's module docstring.
# Generated by `makemigrations core`, hand-renamed from the autodetector's
# default name; operations are untouched.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_postgis_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='deployment_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='site',
            name='live_last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='live_raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='live_site_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='live_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='operational_technologies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='palika',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='site',
            name='palika_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='sitename1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='ward_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
