# Generated by Django 5.2.16 on 2026-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_live_site_directory_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSiteSyncStatus',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_created', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated', models.PositiveIntegerField(blank=True, null=True)),
                ('last_warnings', models.JSONField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'v2_live_site_sync_status',
            },
        ),
    ]
