# Crowdsourced telemetry intake (2026-08-30). Three plain tables plus
# v2_telemetry_samples, which is RANGE-partitioned by `received_at`
# (monthly) — Django's CreateModel can't emit `PARTITION BY`, so that one
# table is done with SeparateDatabaseAndState: Django keeps the model in
# its migration state (ORM works normally), the DB gets the partitioned
# DDL by hand. Retention (prune_telemetry.py) then aggregates and DROPs
# whole expired partitions.
#
# The `telemetry_ensure_partition(date)` plpgsql helper is created here
# and reused by the `ensure_telemetry_partitions` management command to
# roll the window forward each month.

import core.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

_ENSURE_PARTITION_FN = r"""
CREATE OR REPLACE FUNCTION telemetry_ensure_partition(p_month date)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    m_start date := date_trunc('month', p_month)::date;
    m_end   date := (date_trunc('month', p_month) + interval '1 month')::date;
    part    text := format('v2_telemetry_samples_%s', to_char(m_start, 'YYYYMM'));
BEGIN
    IF to_regclass(part) IS NULL THEN
        EXECUTE format(
            'CREATE TABLE %I PARTITION OF v2_telemetry_samples FOR VALUES FROM (%L) TO (%L)',
            part, m_start, m_end
        );
    END IF;
END;
$$;
"""

_CREATE_SAMPLES = r"""
CREATE TABLE v2_telemetry_samples (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    device_id     varchar(64)  NOT NULL,
    ts            timestamptz  NOT NULL,
    received_at   timestamptz  NOT NULL,
    lat           double precision,
    lng           double precision,
    location      geography(Point, 4326),
    gps_accuracy_m real,
    cell_id       bigint,
    pci           integer,
    tac           integer,
    mcc           varchar(6)   NOT NULL DEFAULT '',
    mnc           varchar(6)   NOT NULL DEFAULT '',
    network_type  varchar(12)  NOT NULL DEFAULT 'UNKNOWN',
    rsrp_dbm      smallint,
    rsrq_db       smallint,
    rssi_dbm      smallint,
    sinr_db       smallint,
    battery_pct   smallint,
    trigger_reason varchar(10) NOT NULL DEFAULT 'periodic',
    region        varchar(100) NOT NULL DEFAULT '',
    PRIMARY KEY (id, received_at)
) PARTITION BY RANGE (received_at);

CREATE INDEX v2_telemetry_samples_device_ts_idx ON v2_telemetry_samples (device_id, ts);
CREATE INDEX v2_telemetry_samples_device_idx    ON v2_telemetry_samples (device_id);
CREATE INDEX v2_telemetry_samples_ts_idx        ON v2_telemetry_samples (ts);
CREATE INDEX v2_telemetry_samples_received_idx  ON v2_telemetry_samples (received_at);
CREATE INDEX v2_telemetry_samples_network_idx   ON v2_telemetry_samples (network_type);
CREATE INDEX v2_telemetry_samples_region_idx    ON v2_telemetry_samples (region);
CREATE INDEX v2_telemetry_samples_gix           ON v2_telemetry_samples USING GIST (location);

-- Catch-all so an insert can never fail on a missing month partition
-- (e.g. if the ensure job lapses); prune_telemetry never DROPs this one.
CREATE TABLE v2_telemetry_samples_default PARTITION OF v2_telemetry_samples DEFAULT;

-- Cover a window around the migration date; the ensure command extends it.
DO $$
DECLARE d date;
BEGIN
    FOR d IN
        SELECT generate_series(
            date_trunc('month', now()) - interval '1 month',
            date_trunc('month', now()) + interval '3 months',
            interval '1 month'
        )::date
    LOOP
        PERFORM telemetry_ensure_partition(d);
    END LOOP;
END $$;
"""

_DROP_SAMPLES = r"""
DROP TABLE IF EXISTS v2_telemetry_samples CASCADE;
DROP FUNCTION IF EXISTS telemetry_ensure_partition(date);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_dt_sample_real_signal_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_hash', models.CharField(max_length=64, unique=True)),
                ('key_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('device_count', models.PositiveIntegerField(default=0)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={'db_table': 'v2_telemetry_batches', 'ordering': ['-received_at']},
        ),
        migrations.CreateModel(
            name='TelemetryCoverageBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geohash', models.CharField(db_index=True, max_length=12)),
                ('network_type', models.CharField(default='UNKNOWN', max_length=12)),
                ('region', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('center_lat', models.FloatField(blank=True, null=True)),
                ('center_lng', models.FloatField(blank=True, null=True)),
                ('sample_count', models.BigIntegerField(default=0)),
                ('device_count', models.PositiveIntegerField(default=0)),
                ('rsrp_mean', core.models.SignalFloatField(blank=True, null=True)),
                ('rsrp_p10', core.models.SignalFloatField(blank=True, null=True)),
                ('rsrp_min', models.SmallIntegerField(blank=True, null=True)),
                ('rsrq_mean', core.models.SignalFloatField(blank=True, null=True)),
                ('sinr_mean', core.models.SignalFloatField(blank=True, null=True)),
                ('first_ts', models.DateTimeField(blank=True, null=True)),
                ('last_ts', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'v2_telemetry_coverage_bins',
                'constraints': [models.UniqueConstraint(fields=('geohash', 'network_type'), name='uniq_telemetry_bin')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryIngestKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(db_index=True, max_length=16, unique=True)),
                ('key_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_min', models.PositiveIntegerField(default=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_keys_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'v2_telemetry_ingest_keys', 'ordering': ['-created_at']},
        ),
        migrations.RunSQL(_ENSURE_PARTITION_FN, reverse_sql='DROP FUNCTION IF EXISTS telemetry_ensure_partition(date);'),
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL(_CREATE_SAMPLES, reverse_sql=_DROP_SAMPLES)],
            state_operations=[
                migrations.CreateModel(
                    name='TelemetrySample',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('device_id', models.CharField(db_index=True, max_length=64)),
                        ('ts', models.DateTimeField(db_index=True)),
                        ('received_at', models.DateTimeField(db_index=True)),
                        ('lat', models.FloatField(blank=True, null=True)),
                        ('lng', models.FloatField(blank=True, null=True)),
                        ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                        ('gps_accuracy_m', core.models.SignalFloatField(blank=True, null=True)),
                        ('cell_id', models.BigIntegerField(blank=True, null=True)),
                        ('pci', models.IntegerField(blank=True, null=True)),
                        ('tac', models.IntegerField(blank=True, null=True)),
                        ('mcc', models.CharField(blank=True, default='', max_length=6)),
                        ('mnc', models.CharField(blank=True, default='', max_length=6)),
                        ('network_type', models.CharField(choices=[('LTE', 'LTE'), ('NR', '5G NR'), ('UMTS', 'UMTS'), ('GSM', 'GSM'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=12)),
                        ('rsrp_dbm', models.SmallIntegerField(blank=True, null=True)),
                        ('rsrq_db', models.SmallIntegerField(blank=True, null=True)),
                        ('rssi_dbm', models.SmallIntegerField(blank=True, null=True)),
                        ('sinr_db', models.SmallIntegerField(blank=True, null=True)),
                        ('battery_pct', models.SmallIntegerField(blank=True, null=True)),
                        ('trigger_reason', models.CharField(choices=[('periodic', 'Periodic'), ('handover', 'Handover'), ('manual', 'Manual')], default='periodic', max_length=10)),
                        ('region', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                    ],
                    options={
                        'db_table': 'v2_telemetry_samples',
                        'indexes': [
                            models.Index(fields=['device_id', 'ts'], name='v2_telemetr_device__d75efd_idx'),
                            models.Index(fields=['network_type'], name='v2_telemetr_network_7d1ac4_idx'),
                        ],
                    },
                ),
            ],
        ),
    ]
