# Real `makemigrations` output (2026-09-12), not hand-authored like most
# recent migrations in this repo -- generated for real against a running
# Django 5.2.16 + the actual model state, on the user's local dev stack,
# after 0054 exposed it. Split out from the id-alignment concern below
# on purpose: THIS half (widening three tables' `id` column from
# AutoField/int to BigAutoField/bigint) is unconditionally safe to run
# on every environment -- it's a column-type widen on tables that
# already exist everywhere, not a new table. See
# 0056_drivetestsessionattachment.py's docstring for why THAT one isn't
# safe to blindly run the same way.
#
# Root cause: this app's settings.py sets
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField', but
# 0052_live_site_source.py (LiveSiteSource) and this session's own
# 0054_optimization_activity.py (OptimizationActivity,
# OptimizationActivitySession) were both hand-written by copying an
# older migration's exact `models.AutoField(...)` PK declaration as a
# style template, rather than generated by a real `makemigrations` run
# -- so all three ended up with a 32-bit `id` column that quietly
# disagrees with what the app's own model state actually calls for.
# Harmless in practice at these tables' realistic row counts, but it
# left `makemigrations --check` permanently unable to converge, which
# defeats the whole point of that check as a safety net going forward.
# Aligning them now, while all three tables are either brand new
# (empty) or small (LiveSiteSource, a handful of rows), so the ALTER is
# instant.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_optimization_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesitesource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='optimizationactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='optimizationactivitysession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
