# Generated by Django 5.2.16 on 2026-10-01 11:05 (makemigrations), renamed
# from 0082_auditevent.py for readability. Schema-only -- see AuditEvent's
# own docstring in core/models.py for the full design rationale (why this
# is a separate table from AuthEventLog rather than one shared schema).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_seed_documentation_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('resource', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('resource_id', models.CharField(blank=True, default='', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v2_audit_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
