# Generated by Django 5.2.16 on 2026-10-02 (makemigrations). Schema-only --
# see Sector.Meta.indexes' own comment in core/models.py (2026-10-02 perf
# audit) for why these three: core/dt_serving_cell.py's
# _candidate_sectors() matches every drive-test upload batch against this
# table by pci (4G, alone), scrambling_code (3G, alone), or bcch+bsic
# (2G, together as one composite filter -- hence the composite index
# rather than two more single-column ones), and none of the four had any
# index before this.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_relabel_access_log_menuitem'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['pci'], name='v2_sectors_pci_93a438_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['scrambling_code'], name='v2_sectors_scrambl_a83989_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['bcch', 'bsic'], name='v2_sectors_bcch_5cd74b_idx'),
        ),
    ]
