# Generated by Django 5.2.16 on 2026-10-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_sector_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autheventlog',
            name='event',
            field=models.CharField(choices=[('login_success', 'Local login succeeded'), ('login_failed', 'Local login failed (bad credentials)'), ('login_locked', 'Local login blocked (too many attempts)'), ('login_disabled', 'Local login blocked (account disabled)'), ('sso_login_success', 'SSO login succeeded'), ('sso_login_failed', 'SSO login failed'), ('logout', 'Signed out'), ('pwd_reset_requested', 'Password reset requested'), ('pwd_reset_completed', 'Password reset completed'), ('pwd_changed', 'Password changed (self-service)'), ('mfa_challenge_sent', 'MFA challenge issued'), ('mfa_verify_failed', 'MFA code rejected'), ('recaptcha_failed', 'reCAPTCHA check failed')], db_index=True, max_length=20),
        ),
    ]
