# Generated by Django 5.2.16 on 2026-10-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_autheventlog_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('mfa_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'v2_security_settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='autheventlog',
            name='event',
            field=models.CharField(choices=[('login_success', 'Local login succeeded'), ('login_failed', 'Local login failed (bad credentials)'), ('login_locked', 'Local login blocked (too many attempts)'), ('login_disabled', 'Local login blocked (account disabled)'), ('sso_login_success', 'SSO login succeeded'), ('sso_login_failed', 'SSO login failed'), ('logout', 'Signed out'), ('pwd_reset_requested', 'Password reset requested'), ('pwd_reset_completed', 'Password reset completed'), ('pwd_changed', 'Password changed (self-service)'), ('mfa_challenge_sent', 'MFA challenge issued'), ('mfa_verify_failed', 'MFA code rejected'), ('mfa_enrolled', 'MFA enrolled'), ('mfa_disabled', 'MFA disabled'), ('recaptcha_failed', 'reCAPTCHA check failed')], db_index=True, max_length=20),
        ),
    ]
