# Generated by Django 5.2.16 on 2026-10-02 11:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_mfa_security_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolteCallSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('ts', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('cell_id', models.BigIntegerField(blank=True, null=True)),
                ('pci', models.IntegerField(blank=True, null=True)),
                ('tac', models.IntegerField(blank=True, null=True)),
                ('mcc', models.CharField(blank=True, default='', max_length=6)),
                ('mnc', models.CharField(blank=True, default='', max_length=6)),
                ('network_type', models.CharField(choices=[('LTE', 'LTE (VoLTE)'), ('NR', '5G NR (VoNR)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=12)),
                ('call_duration_s', models.IntegerField(blank=True, null=True)),
                ('codec', models.CharField(blank=True, default='', max_length=20)),
                ('packet_loss_pct', models.FloatField(blank=True, null=True)),
                ('jitter_ms', models.FloatField(blank=True, null=True)),
                ('rtt_ms', models.FloatField(blank=True, null=True)),
                ('quality_level', models.CharField(blank=True, default='', max_length=20)),
                ('r_factor', models.FloatField(blank=True, null=True)),
                ('mos_estimate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v2_volte_call_samples',
                'indexes': [models.Index(fields=['device_id', 'ts'], name='v2_volte_ca_device__07affc_idx'), models.Index(fields=['network_type'], name='v2_volte_ca_network_c97578_idx')],
            },
        ),
    ]
