# Generated by Django 5.2.16 on 2026-10-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_seed_volte_quality_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='voltecallsample',
            name='mos_is_provisional',
            field=models.BooleanField(default=False),
        ),
    ]
