# Generated by Django 5.2.16 on 2026-10-02 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_volte_mos_provisional'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v2_blocked_ips',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.AlterField(
            model_name='autheventlog',
            name='event',
            field=models.CharField(choices=[('login_success', 'Local login succeeded'), ('login_failed', 'Local login failed (bad credentials)'), ('login_locked', 'Local login blocked (too many attempts)'), ('login_disabled', 'Local login blocked (account disabled)'), ('sso_login_success', 'SSO login succeeded'), ('sso_login_failed', 'SSO login failed'), ('logout', 'Signed out'), ('pwd_reset_requested', 'Password reset requested'), ('pwd_reset_completed', 'Password reset completed'), ('pwd_changed', 'Password changed (self-service)'), ('mfa_challenge_sent', 'MFA challenge issued'), ('mfa_verify_failed', 'MFA code rejected'), ('mfa_enrolled', 'MFA enrolled'), ('mfa_disabled', 'MFA disabled'), ('recaptcha_failed', 'reCAPTCHA check failed'), ('login_ip_blocked', 'Login blocked (IP auto-blocked)')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='autheventlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='v2_auth_eve_ip_addr_efd91f_idx'),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='unblocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
