# Generated by Django 5.2.16 on 2026-10-05 10:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_trace_phone_attestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(max_length=64, unique=True)),
                ('msisdn_enc', models.TextField(blank=True, default='')),
                ('msisdn_lookup', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('imei_enc', models.TextField(blank=True, default='')),
                ('phone_model', models.CharField(blank=True, default='', max_length=80)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=80)),
                ('user_type', models.CharField(choices=[('general', 'General user'), ('employee', 'NTC employee')], default='general', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'v2_device_identity',
            },
        ),
        migrations.AddField(
            model_name='tracerequest',
            name='kind',
            field=models.CharField(choices=[('investigation', 'Subscriber investigation'), ('case', 'Case')], default='case', max_length=16),
        ),
        migrations.AlterField(
            model_name='tracerequest',
            name='case_reference',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='EmergencyDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v2_emergency_declaration',
                'ordering': ['-declared_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('crowd_drive', 'Crowd drive'), ('staff_drive', 'Staff drive'), ('operator_investigation', 'Operator investigation'), ('operator_case', 'Operator case'), ('drive_test', 'Drive test (team)')], max_length=24)),
                ('device_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('drive_session_id', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('user_type', models.CharField(default='general', max_length=10)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sample_at', models.DateTimeField(blank=True, null=True)),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_sessions', to='core.tracerequest')),
            ],
            options={
                'db_table': 'v2_collection_session',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', 'started_at'], name='v2_coll_source_started_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.role')),
            ],
            options={
                'db_table': 'v2_role_permission',
                'constraints': [models.UniqueConstraint(fields=('role', 'code'), name='uniq_role_permission')],
            },
        ),
    ]
