# Generated by Django 5.2.16 on 2026-10-05 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_identity_sessions_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracelocationsample',
            name='cell_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracelocationsample',
            name='cqi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracelocationsample',
            name='mcc',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='tracelocationsample',
            name='mnc',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='tracelocationsample',
            name='network_type',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='tracelocationsample',
            name='pci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracelocationsample',
            name='rsrp_dbm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracelocationsample',
            name='rsrq_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracelocationsample',
            name='rssi_dbm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracelocationsample',
            name='sinr_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracelocationsample',
            name='tac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TraceSpeedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField()),
                ('ping_median_ms', models.FloatField(blank=True, null=True)),
                ('jitter_ms', models.FloatField(blank=True, null=True)),
                ('download_mbps', models.FloatField(blank=True, null=True)),
                ('upload_mbps', models.FloatField(blank=True, null=True)),
                ('network_type', models.CharField(blank=True, default='', max_length=8)),
                ('rsrp_dbm', models.IntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_results', to='core.tracerequest')),
            ],
            options={
                'db_table': 'v2_trace_speed_result',
                'ordering': ['ran_at'],
            },
        ),
    ]
