# Generated by Django 5.2.16 on 2026-10-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_trace_qos_speedtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REVOKED', 'Revoked by user'), ('COMPLETED', 'Completed by operator')], default='PENDING', max_length=12),
        ),
    ]
