# Generated by Django 5.2.16 on 2026-10-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_trace_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
