# Generated by Django 5.2.16 on 2026-10-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_telemetry_speed_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrydrivetestsession',
            name='max_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
