# Generated by Django 5.2.16 on 2026-10-08 04:02, backfill step added by hand.
#
# The backfill recomputes EVERY existing row's msisdn_lookup, not just
# fills in the new imei_lookup column -- msisdn_lookup_key() changed in
# this same change (core/collection.py) to canonicalize through
# rescue.py's _clean_msisdn before hashing, so any row whose stored
# msisdn needed canonicalizing (e.g. a bare local number) now has a
# STALE hash under the old formula that would never match a correctly
# canonicalized search again. Decrypts each row's own msisdn_enc/
# imei_enc (there is no other way to recompute a keyed hash of secret
# data) rather than touching the ciphertext itself.
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_lookup_hashes(apps, schema_editor):
    DeviceIdentity = apps.get_model('core', 'DeviceIdentity')
    from core.mfa import decrypt_secret
    from core.collection import imei_lookup_key, msisdn_lookup_key

    for identity in DeviceIdentity.objects.exclude(msisdn_enc='').iterator():
        raw = decrypt_secret(identity.msisdn_enc)
        if raw:
            identity.msisdn_lookup = msisdn_lookup_key(raw)
            identity.save(update_fields=['msisdn_lookup'])
    for identity in DeviceIdentity.objects.exclude(imei_enc='').iterator():
        raw = decrypt_secret(identity.imei_enc)
        if raw:
            identity.imei_lookup = imei_lookup_key(raw)
            identity.save(update_fields=['imei_lookup'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_seed_rescue_enrolled_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceidentity',
            name='imei_lookup',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='DeviceLocationTraceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(max_length=10)),
                ('query_value', models.CharField(max_length=32)),
                ('found', models.BooleanField(default=False)),
                ('queried_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('looked_up_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_location_traces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v2_device_location_trace_log',
                'ordering': ['-queried_at'],
            },
        ),
        migrations.RunPython(backfill_lookup_hashes, noop),
    ]
