# Generated by Django 5.2.16 on 2026-10-08 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_seed_registered_devices_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('fcm_token', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'v2_telemetry_push_token',
            },
        ),
        migrations.AlterField(
            model_name='telemetrysample',
            name='trigger_reason',
            field=models.CharField(choices=[('periodic', 'Periodic'), ('handover', 'Handover'), ('manual', 'Manual'), ('drive', 'Drive test'), ('drive_start', 'Drive start'), ('drive_stop', 'Drive stop'), ('on_demand', 'On demand')], default='periodic', max_length=16),
        ),
        migrations.CreateModel(
            name='AreaSampleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius_km', models.FloatField()),
                ('lookback_hours', models.PositiveSmallIntegerField(default=24)),
                ('devices_in_area', models.PositiveIntegerField(default=0)),
                ('pushes_sent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_sample_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v2_area_sample_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
