# Generated by Django 5.2.16 on 2026-10-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_seed_area_sample_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelocationtracelog',
            name='case_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='devicelocationtracelog',
            name='emergency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_location_traces', to='core.emergencydeclaration'),
        ),
    ]
