# Generated by Django 5.2.18 on 2026-10-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_device_trace_case_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(db_index=True, max_length=20)),
                ('device_hash', models.CharField(db_index=True, max_length=64)),
                ('hardware_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=80)),
                ('phone_model', models.CharField(blank=True, default='', max_length=80)),
                ('app_version', models.CharField(blank=True, default='', max_length=40)),
                ('linked_via', models.JSONField(blank=True, default=list)),
                ('number_verified_by', models.CharField(choices=[('self_declared', 'Typed by the user'), ('sim_read', 'Read from the SIM'), ('sms_code', 'Confirmed by SMS code')], default='self_declared', max_length=20)),
                ('first_linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'v2_subscriber_device',
                'constraints': [models.UniqueConstraint(fields=('msisdn', 'device_hash'), name='uniq_subscriber_device')],
            },
        ),
    ]
